language: rust
os:
  - linux
  - osx
rust:
  - nightly
notifications:
  email: false
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
  - export PATH=$PATH:~/.cargo/bin
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo +nightly fmt --all -- --write-mode=diff
  - cargo +nightly clippy --all -- --deny warnings