[package]
name = "enum-str-derive"
version = "0.1.0"
authors = ["Victor Porof <victor.porof@gmail.com>"]
edition = "2018"

[lib]
name = "enum_str_derive"
proc-macro = true

[dependencies]
heck = "0.3"
quote = "0.6"
syn = "0.15"
proc-macro2 = "0.4"